(dp1
S'output'
p2
S"<type 'exceptions.NameError'> global name 'self' is not defined"
p3
sS'layer'
p4
S'/home/july/Escritorio/LabDesarrolloSoftware/applications/LabDS/controllers/default.py'
p5
sS'code'
p6
S'<code object <module> at 0x7f2c3365f330, file "/home/july/Escritorio/LabDesarrolloSoftware/applications/LabDS/controllers/default.py", line 3>'
p7
sS'snapshot'
p8
(dp9
sS'traceback'
p10
S'Traceback (most recent call last):\n  File "/home/july/Escritorio/LabDesarrolloSoftware/gluon/restricted.py", line 219, in restricted\n    exec(ccode, environment)\n  File "/home/july/Escritorio/LabDesarrolloSoftware/applications/LabDS/controllers/default.py", line 69, in <module>\n  File "/home/july/Escritorio/LabDesarrolloSoftware/gluon/globals.py", line 419, in <lambda>\n    self._caller = lambda f: f()\n  File "/home/july/Escritorio/LabDesarrolloSoftware/applications/LabDS/controllers/default.py", line 19, in index\n    return dict(message=T(self.data))\nNameError: global name \'self\' is not defined\n'
p11
s.